# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.3/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/bertin/clionprojects/COEN243

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/bertin/clionprojects/COEN243

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bertin/clionprojects/COEN243/CMakeFiles /Users/bertin/clionprojects/COEN243//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bertin/clionprojects/COEN243/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 2DArrays.cpp

# Build rule for target.
2DArrays.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 2DArrays.cpp
.PHONY : 2DArrays.cpp

# fast build rule for target.
2DArrays.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/2DArrays.cpp.dir/build.make CMakeFiles/2DArrays.cpp.dir/build
.PHONY : 2DArrays.cpp/fast

#=============================================================================
# Target rules for targets named 3.1_backup.cpp

# Build rule for target.
3.1_backup.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 3.1_backup.cpp
.PHONY : 3.1_backup.cpp

# fast build rule for target.
3.1_backup.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3.1_backup.cpp.dir/build.make CMakeFiles/3.1_backup.cpp.dir/build
.PHONY : 3.1_backup.cpp/fast

#=============================================================================
# Target rules for targets named Arrays.cpp

# Build rule for target.
Arrays.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Arrays.cpp
.PHONY : Arrays.cpp

# fast build rule for target.
Arrays.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arrays.cpp.dir/build.make CMakeFiles/Arrays.cpp.dir/build
.PHONY : Arrays.cpp/fast

#=============================================================================
# Target rules for targets named Ass3_1.cpp

# Build rule for target.
Ass3_1.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Ass3_1.cpp
.PHONY : Ass3_1.cpp

# fast build rule for target.
Ass3_1.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ass3_1.cpp.dir/build.make CMakeFiles/Ass3_1.cpp.dir/build
.PHONY : Ass3_1.cpp/fast

#=============================================================================
# Target rules for targets named Assignment4_1.cpp

# Build rule for target.
Assignment4_1.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Assignment4_1.cpp
.PHONY : Assignment4_1.cpp

# fast build rule for target.
Assignment4_1.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assignment4_1.cpp.dir/build.make CMakeFiles/Assignment4_1.cpp.dir/build
.PHONY : Assignment4_1.cpp/fast

#=============================================================================
# Target rules for targets named Circles.cpp

# Build rule for target.
Circles.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Circles.cpp
.PHONY : Circles.cpp

# fast build rule for target.
Circles.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Circles.cpp.dir/build.make CMakeFiles/Circles.cpp.dir/build
.PHONY : Circles.cpp/fast

#=============================================================================
# Target rules for targets named DynamicMemoryMgmt.cpp

# Build rule for target.
DynamicMemoryMgmt.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DynamicMemoryMgmt.cpp
.PHONY : DynamicMemoryMgmt.cpp

# fast build rule for target.
DynamicMemoryMgmt.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DynamicMemoryMgmt.cpp.dir/build.make CMakeFiles/DynamicMemoryMgmt.cpp.dir/build
.PHONY : DynamicMemoryMgmt.cpp/fast

#=============================================================================
# Target rules for targets named ExceptionHandler.cpp

# Build rule for target.
ExceptionHandler.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExceptionHandler.cpp
.PHONY : ExceptionHandler.cpp

# fast build rule for target.
ExceptionHandler.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExceptionHandler.cpp.dir/build.make CMakeFiles/ExceptionHandler.cpp.dir/build
.PHONY : ExceptionHandler.cpp/fast

#=============================================================================
# Target rules for targets named IO.cpp

# Build rule for target.
IO.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IO.cpp
.PHONY : IO.cpp

# fast build rule for target.
IO.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IO.cpp.dir/build.make CMakeFiles/IO.cpp.dir/build
.PHONY : IO.cpp/fast

#=============================================================================
# Target rules for targets named IO2.cpp

# Build rule for target.
IO2.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 IO2.cpp
.PHONY : IO2.cpp

# fast build rule for target.
IO2.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IO2.cpp.dir/build.make CMakeFiles/IO2.cpp.dir/build
.PHONY : IO2.cpp/fast

#=============================================================================
# Target rules for targets named MyClass.cpp

# Build rule for target.
MyClass.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MyClass.cpp
.PHONY : MyClass.cpp

# fast build rule for target.
MyClass.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyClass.cpp.dir/build.make CMakeFiles/MyClass.cpp.dir/build
.PHONY : MyClass.cpp/fast

#=============================================================================
# Target rules for targets named Palindrome.cpp

# Build rule for target.
Palindrome.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Palindrome.cpp
.PHONY : Palindrome.cpp

# fast build rule for target.
Palindrome.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Palindrome.cpp.dir/build.make CMakeFiles/Palindrome.cpp.dir/build
.PHONY : Palindrome.cpp/fast

#=============================================================================
# Target rules for targets named Pointers.cpp

# Build rule for target.
Pointers.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Pointers.cpp
.PHONY : Pointers.cpp

# fast build rule for target.
Pointers.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pointers.cpp.dir/build.make CMakeFiles/Pointers.cpp.dir/build
.PHONY : Pointers.cpp/fast

#=============================================================================
# Target rules for targets named PointersDemo.cpp

# Build rule for target.
PointersDemo.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PointersDemo.cpp
.PHONY : PointersDemo.cpp

# fast build rule for target.
PointersDemo.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PointersDemo.cpp.dir/build.make CMakeFiles/PointersDemo.cpp.dir/build
.PHONY : PointersDemo.cpp/fast

#=============================================================================
# Target rules for targets named RecursiveFunctions.cpp

# Build rule for target.
RecursiveFunctions.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RecursiveFunctions.cpp
.PHONY : RecursiveFunctions.cpp

# fast build rule for target.
RecursiveFunctions.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RecursiveFunctions.cpp.dir/build.make CMakeFiles/RecursiveFunctions.cpp.dir/build
.PHONY : RecursiveFunctions.cpp/fast

#=============================================================================
# Target rules for targets named STL_Sort.cpp

# Build rule for target.
STL_Sort.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 STL_Sort.cpp
.PHONY : STL_Sort.cpp

# fast build rule for target.
STL_Sort.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STL_Sort.cpp.dir/build.make CMakeFiles/STL_Sort.cpp.dir/build
.PHONY : STL_Sort.cpp/fast

#=============================================================================
# Target rules for targets named StringsManipulation.cpp

# Build rule for target.
StringsManipulation.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 StringsManipulation.cpp
.PHONY : StringsManipulation.cpp

# fast build rule for target.
StringsManipulation.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StringsManipulation.cpp.dir/build.make CMakeFiles/StringsManipulation.cpp.dir/build
.PHONY : StringsManipulation.cpp/fast

#=============================================================================
# Target rules for targets named StructDemo.cpp

# Build rule for target.
StructDemo.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 StructDemo.cpp
.PHONY : StructDemo.cpp

# fast build rule for target.
StructDemo.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StructDemo.cpp.dir/build.make CMakeFiles/StructDemo.cpp.dir/build
.PHONY : StructDemo.cpp/fast

#=============================================================================
# Target rules for targets named Vectors.cpp

# Build rule for target.
Vectors.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Vectors.cpp
.PHONY : Vectors.cpp

# fast build rule for target.
Vectors.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vectors.cpp.dir/build.make CMakeFiles/Vectors.cpp.dir/build
.PHONY : Vectors.cpp/fast

#=============================================================================
# Target rules for targets named cpp_templates.cpp

# Build rule for target.
cpp_templates.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cpp_templates.cpp
.PHONY : cpp_templates.cpp

# fast build rule for target.
cpp_templates.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp_templates.cpp.dir/build.make CMakeFiles/cpp_templates.cpp.dir/build
.PHONY : cpp_templates.cpp/fast

#=============================================================================
# Target rules for targets named main.cpp

# Build rule for target.
main.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main.cpp
.PHONY : main.cpp

# fast build rule for target.
main.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.cpp.dir/build.make CMakeFiles/main.cpp.dir/build
.PHONY : main.cpp/fast

#=============================================================================
# Target rules for targets named mainmain.cpp

# Build rule for target.
mainmain.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mainmain.cpp
.PHONY : mainmain.cpp

# fast build rule for target.
mainmain.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainmain.cpp.dir/build.make CMakeFiles/mainmain.cpp.dir/build
.PHONY : mainmain.cpp/fast

#=============================================================================
# Target rules for targets named smartpointers.cpp

# Build rule for target.
smartpointers.cpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 smartpointers.cpp
.PHONY : smartpointers.cpp

# fast build rule for target.
smartpointers.cpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smartpointers.cpp.dir/build.make CMakeFiles/smartpointers.cpp.dir/build
.PHONY : smartpointers.cpp/fast

#=============================================================================
# Target rules for targets named stacks

# Build rule for target.
stacks: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stacks
.PHONY : stacks

# fast build rule for target.
stacks/fast:
	$(MAKE) $(MAKESILENT) -f STL/CMakeFiles/stacks.dir/build.make STL/CMakeFiles/stacks.dir/build
.PHONY : stacks/fast

2DArrays.o: 2DArrays.cpp.o
.PHONY : 2DArrays.o

# target to build an object file
2DArrays.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/2DArrays.cpp.dir/build.make CMakeFiles/2DArrays.cpp.dir/2DArrays.cpp.o
.PHONY : 2DArrays.cpp.o

2DArrays.i: 2DArrays.cpp.i
.PHONY : 2DArrays.i

# target to preprocess a source file
2DArrays.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/2DArrays.cpp.dir/build.make CMakeFiles/2DArrays.cpp.dir/2DArrays.cpp.i
.PHONY : 2DArrays.cpp.i

2DArrays.s: 2DArrays.cpp.s
.PHONY : 2DArrays.s

# target to generate assembly for a file
2DArrays.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/2DArrays.cpp.dir/build.make CMakeFiles/2DArrays.cpp.dir/2DArrays.cpp.s
.PHONY : 2DArrays.cpp.s

3.1_backup.o: 3.1_backup.cpp.o
.PHONY : 3.1_backup.o

# target to build an object file
3.1_backup.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3.1_backup.cpp.dir/build.make CMakeFiles/3.1_backup.cpp.dir/3.1_backup.cpp.o
.PHONY : 3.1_backup.cpp.o

3.1_backup.i: 3.1_backup.cpp.i
.PHONY : 3.1_backup.i

# target to preprocess a source file
3.1_backup.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3.1_backup.cpp.dir/build.make CMakeFiles/3.1_backup.cpp.dir/3.1_backup.cpp.i
.PHONY : 3.1_backup.cpp.i

3.1_backup.s: 3.1_backup.cpp.s
.PHONY : 3.1_backup.s

# target to generate assembly for a file
3.1_backup.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/3.1_backup.cpp.dir/build.make CMakeFiles/3.1_backup.cpp.dir/3.1_backup.cpp.s
.PHONY : 3.1_backup.cpp.s

Arrays.o: Arrays.cpp.o
.PHONY : Arrays.o

# target to build an object file
Arrays.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arrays.cpp.dir/build.make CMakeFiles/Arrays.cpp.dir/Arrays.cpp.o
.PHONY : Arrays.cpp.o

Arrays.i: Arrays.cpp.i
.PHONY : Arrays.i

# target to preprocess a source file
Arrays.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arrays.cpp.dir/build.make CMakeFiles/Arrays.cpp.dir/Arrays.cpp.i
.PHONY : Arrays.cpp.i

Arrays.s: Arrays.cpp.s
.PHONY : Arrays.s

# target to generate assembly for a file
Arrays.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Arrays.cpp.dir/build.make CMakeFiles/Arrays.cpp.dir/Arrays.cpp.s
.PHONY : Arrays.cpp.s

Ass3_1.o: Ass3_1.cpp.o
.PHONY : Ass3_1.o

# target to build an object file
Ass3_1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ass3_1.cpp.dir/build.make CMakeFiles/Ass3_1.cpp.dir/Ass3_1.cpp.o
.PHONY : Ass3_1.cpp.o

Ass3_1.i: Ass3_1.cpp.i
.PHONY : Ass3_1.i

# target to preprocess a source file
Ass3_1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ass3_1.cpp.dir/build.make CMakeFiles/Ass3_1.cpp.dir/Ass3_1.cpp.i
.PHONY : Ass3_1.cpp.i

Ass3_1.s: Ass3_1.cpp.s
.PHONY : Ass3_1.s

# target to generate assembly for a file
Ass3_1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Ass3_1.cpp.dir/build.make CMakeFiles/Ass3_1.cpp.dir/Ass3_1.cpp.s
.PHONY : Ass3_1.cpp.s

Assignment4_1.o: Assignment4_1.cpp.o
.PHONY : Assignment4_1.o

# target to build an object file
Assignment4_1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assignment4_1.cpp.dir/build.make CMakeFiles/Assignment4_1.cpp.dir/Assignment4_1.cpp.o
.PHONY : Assignment4_1.cpp.o

Assignment4_1.i: Assignment4_1.cpp.i
.PHONY : Assignment4_1.i

# target to preprocess a source file
Assignment4_1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assignment4_1.cpp.dir/build.make CMakeFiles/Assignment4_1.cpp.dir/Assignment4_1.cpp.i
.PHONY : Assignment4_1.cpp.i

Assignment4_1.s: Assignment4_1.cpp.s
.PHONY : Assignment4_1.s

# target to generate assembly for a file
Assignment4_1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Assignment4_1.cpp.dir/build.make CMakeFiles/Assignment4_1.cpp.dir/Assignment4_1.cpp.s
.PHONY : Assignment4_1.cpp.s

Circles.o: Circles.cpp.o
.PHONY : Circles.o

# target to build an object file
Circles.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Circles.cpp.dir/build.make CMakeFiles/Circles.cpp.dir/Circles.cpp.o
.PHONY : Circles.cpp.o

Circles.i: Circles.cpp.i
.PHONY : Circles.i

# target to preprocess a source file
Circles.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Circles.cpp.dir/build.make CMakeFiles/Circles.cpp.dir/Circles.cpp.i
.PHONY : Circles.cpp.i

Circles.s: Circles.cpp.s
.PHONY : Circles.s

# target to generate assembly for a file
Circles.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Circles.cpp.dir/build.make CMakeFiles/Circles.cpp.dir/Circles.cpp.s
.PHONY : Circles.cpp.s

DynamicMemoryMgmt.o: DynamicMemoryMgmt.cpp.o
.PHONY : DynamicMemoryMgmt.o

# target to build an object file
DynamicMemoryMgmt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DynamicMemoryMgmt.cpp.dir/build.make CMakeFiles/DynamicMemoryMgmt.cpp.dir/DynamicMemoryMgmt.cpp.o
.PHONY : DynamicMemoryMgmt.cpp.o

DynamicMemoryMgmt.i: DynamicMemoryMgmt.cpp.i
.PHONY : DynamicMemoryMgmt.i

# target to preprocess a source file
DynamicMemoryMgmt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DynamicMemoryMgmt.cpp.dir/build.make CMakeFiles/DynamicMemoryMgmt.cpp.dir/DynamicMemoryMgmt.cpp.i
.PHONY : DynamicMemoryMgmt.cpp.i

DynamicMemoryMgmt.s: DynamicMemoryMgmt.cpp.s
.PHONY : DynamicMemoryMgmt.s

# target to generate assembly for a file
DynamicMemoryMgmt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DynamicMemoryMgmt.cpp.dir/build.make CMakeFiles/DynamicMemoryMgmt.cpp.dir/DynamicMemoryMgmt.cpp.s
.PHONY : DynamicMemoryMgmt.cpp.s

ExceptionHandler.o: ExceptionHandler.cpp.o
.PHONY : ExceptionHandler.o

# target to build an object file
ExceptionHandler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExceptionHandler.cpp.dir/build.make CMakeFiles/ExceptionHandler.cpp.dir/ExceptionHandler.cpp.o
.PHONY : ExceptionHandler.cpp.o

ExceptionHandler.i: ExceptionHandler.cpp.i
.PHONY : ExceptionHandler.i

# target to preprocess a source file
ExceptionHandler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExceptionHandler.cpp.dir/build.make CMakeFiles/ExceptionHandler.cpp.dir/ExceptionHandler.cpp.i
.PHONY : ExceptionHandler.cpp.i

ExceptionHandler.s: ExceptionHandler.cpp.s
.PHONY : ExceptionHandler.s

# target to generate assembly for a file
ExceptionHandler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ExceptionHandler.cpp.dir/build.make CMakeFiles/ExceptionHandler.cpp.dir/ExceptionHandler.cpp.s
.PHONY : ExceptionHandler.cpp.s

IO.o: IO.cpp.o
.PHONY : IO.o

# target to build an object file
IO.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IO.cpp.dir/build.make CMakeFiles/IO.cpp.dir/IO.cpp.o
.PHONY : IO.cpp.o

IO.i: IO.cpp.i
.PHONY : IO.i

# target to preprocess a source file
IO.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IO.cpp.dir/build.make CMakeFiles/IO.cpp.dir/IO.cpp.i
.PHONY : IO.cpp.i

IO.s: IO.cpp.s
.PHONY : IO.s

# target to generate assembly for a file
IO.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IO.cpp.dir/build.make CMakeFiles/IO.cpp.dir/IO.cpp.s
.PHONY : IO.cpp.s

IO2.o: IO2.cpp.o
.PHONY : IO2.o

# target to build an object file
IO2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IO2.cpp.dir/build.make CMakeFiles/IO2.cpp.dir/IO2.cpp.o
.PHONY : IO2.cpp.o

IO2.i: IO2.cpp.i
.PHONY : IO2.i

# target to preprocess a source file
IO2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IO2.cpp.dir/build.make CMakeFiles/IO2.cpp.dir/IO2.cpp.i
.PHONY : IO2.cpp.i

IO2.s: IO2.cpp.s
.PHONY : IO2.s

# target to generate assembly for a file
IO2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/IO2.cpp.dir/build.make CMakeFiles/IO2.cpp.dir/IO2.cpp.s
.PHONY : IO2.cpp.s

MyClass.o: MyClass.cpp.o
.PHONY : MyClass.o

# target to build an object file
MyClass.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyClass.cpp.dir/build.make CMakeFiles/MyClass.cpp.dir/MyClass.cpp.o
.PHONY : MyClass.cpp.o

MyClass.i: MyClass.cpp.i
.PHONY : MyClass.i

# target to preprocess a source file
MyClass.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyClass.cpp.dir/build.make CMakeFiles/MyClass.cpp.dir/MyClass.cpp.i
.PHONY : MyClass.cpp.i

MyClass.s: MyClass.cpp.s
.PHONY : MyClass.s

# target to generate assembly for a file
MyClass.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyClass.cpp.dir/build.make CMakeFiles/MyClass.cpp.dir/MyClass.cpp.s
.PHONY : MyClass.cpp.s

Palindrome.o: Palindrome.cpp.o
.PHONY : Palindrome.o

# target to build an object file
Palindrome.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Palindrome.cpp.dir/build.make CMakeFiles/Palindrome.cpp.dir/Palindrome.cpp.o
.PHONY : Palindrome.cpp.o

Palindrome.i: Palindrome.cpp.i
.PHONY : Palindrome.i

# target to preprocess a source file
Palindrome.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Palindrome.cpp.dir/build.make CMakeFiles/Palindrome.cpp.dir/Palindrome.cpp.i
.PHONY : Palindrome.cpp.i

Palindrome.s: Palindrome.cpp.s
.PHONY : Palindrome.s

# target to generate assembly for a file
Palindrome.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Palindrome.cpp.dir/build.make CMakeFiles/Palindrome.cpp.dir/Palindrome.cpp.s
.PHONY : Palindrome.cpp.s

Pointers.o: Pointers.cpp.o
.PHONY : Pointers.o

# target to build an object file
Pointers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pointers.cpp.dir/build.make CMakeFiles/Pointers.cpp.dir/Pointers.cpp.o
.PHONY : Pointers.cpp.o

Pointers.i: Pointers.cpp.i
.PHONY : Pointers.i

# target to preprocess a source file
Pointers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pointers.cpp.dir/build.make CMakeFiles/Pointers.cpp.dir/Pointers.cpp.i
.PHONY : Pointers.cpp.i

Pointers.s: Pointers.cpp.s
.PHONY : Pointers.s

# target to generate assembly for a file
Pointers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pointers.cpp.dir/build.make CMakeFiles/Pointers.cpp.dir/Pointers.cpp.s
.PHONY : Pointers.cpp.s

PointersDemo.o: PointersDemo.cpp.o
.PHONY : PointersDemo.o

# target to build an object file
PointersDemo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PointersDemo.cpp.dir/build.make CMakeFiles/PointersDemo.cpp.dir/PointersDemo.cpp.o
.PHONY : PointersDemo.cpp.o

PointersDemo.i: PointersDemo.cpp.i
.PHONY : PointersDemo.i

# target to preprocess a source file
PointersDemo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PointersDemo.cpp.dir/build.make CMakeFiles/PointersDemo.cpp.dir/PointersDemo.cpp.i
.PHONY : PointersDemo.cpp.i

PointersDemo.s: PointersDemo.cpp.s
.PHONY : PointersDemo.s

# target to generate assembly for a file
PointersDemo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PointersDemo.cpp.dir/build.make CMakeFiles/PointersDemo.cpp.dir/PointersDemo.cpp.s
.PHONY : PointersDemo.cpp.s

RecursiveFunctions.o: RecursiveFunctions.cpp.o
.PHONY : RecursiveFunctions.o

# target to build an object file
RecursiveFunctions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RecursiveFunctions.cpp.dir/build.make CMakeFiles/RecursiveFunctions.cpp.dir/RecursiveFunctions.cpp.o
.PHONY : RecursiveFunctions.cpp.o

RecursiveFunctions.i: RecursiveFunctions.cpp.i
.PHONY : RecursiveFunctions.i

# target to preprocess a source file
RecursiveFunctions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RecursiveFunctions.cpp.dir/build.make CMakeFiles/RecursiveFunctions.cpp.dir/RecursiveFunctions.cpp.i
.PHONY : RecursiveFunctions.cpp.i

RecursiveFunctions.s: RecursiveFunctions.cpp.s
.PHONY : RecursiveFunctions.s

# target to generate assembly for a file
RecursiveFunctions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RecursiveFunctions.cpp.dir/build.make CMakeFiles/RecursiveFunctions.cpp.dir/RecursiveFunctions.cpp.s
.PHONY : RecursiveFunctions.cpp.s

STL_Sort.o: STL_Sort.cpp.o
.PHONY : STL_Sort.o

# target to build an object file
STL_Sort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STL_Sort.cpp.dir/build.make CMakeFiles/STL_Sort.cpp.dir/STL_Sort.cpp.o
.PHONY : STL_Sort.cpp.o

STL_Sort.i: STL_Sort.cpp.i
.PHONY : STL_Sort.i

# target to preprocess a source file
STL_Sort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STL_Sort.cpp.dir/build.make CMakeFiles/STL_Sort.cpp.dir/STL_Sort.cpp.i
.PHONY : STL_Sort.cpp.i

STL_Sort.s: STL_Sort.cpp.s
.PHONY : STL_Sort.s

# target to generate assembly for a file
STL_Sort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/STL_Sort.cpp.dir/build.make CMakeFiles/STL_Sort.cpp.dir/STL_Sort.cpp.s
.PHONY : STL_Sort.cpp.s

StringsManipulation.o: StringsManipulation.cpp.o
.PHONY : StringsManipulation.o

# target to build an object file
StringsManipulation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StringsManipulation.cpp.dir/build.make CMakeFiles/StringsManipulation.cpp.dir/StringsManipulation.cpp.o
.PHONY : StringsManipulation.cpp.o

StringsManipulation.i: StringsManipulation.cpp.i
.PHONY : StringsManipulation.i

# target to preprocess a source file
StringsManipulation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StringsManipulation.cpp.dir/build.make CMakeFiles/StringsManipulation.cpp.dir/StringsManipulation.cpp.i
.PHONY : StringsManipulation.cpp.i

StringsManipulation.s: StringsManipulation.cpp.s
.PHONY : StringsManipulation.s

# target to generate assembly for a file
StringsManipulation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StringsManipulation.cpp.dir/build.make CMakeFiles/StringsManipulation.cpp.dir/StringsManipulation.cpp.s
.PHONY : StringsManipulation.cpp.s

StructDemo.o: StructDemo.cpp.o
.PHONY : StructDemo.o

# target to build an object file
StructDemo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StructDemo.cpp.dir/build.make CMakeFiles/StructDemo.cpp.dir/StructDemo.cpp.o
.PHONY : StructDemo.cpp.o

StructDemo.i: StructDemo.cpp.i
.PHONY : StructDemo.i

# target to preprocess a source file
StructDemo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StructDemo.cpp.dir/build.make CMakeFiles/StructDemo.cpp.dir/StructDemo.cpp.i
.PHONY : StructDemo.cpp.i

StructDemo.s: StructDemo.cpp.s
.PHONY : StructDemo.s

# target to generate assembly for a file
StructDemo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/StructDemo.cpp.dir/build.make CMakeFiles/StructDemo.cpp.dir/StructDemo.cpp.s
.PHONY : StructDemo.cpp.s

Vectors.o: Vectors.cpp.o
.PHONY : Vectors.o

# target to build an object file
Vectors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vectors.cpp.dir/build.make CMakeFiles/Vectors.cpp.dir/Vectors.cpp.o
.PHONY : Vectors.cpp.o

Vectors.i: Vectors.cpp.i
.PHONY : Vectors.i

# target to preprocess a source file
Vectors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vectors.cpp.dir/build.make CMakeFiles/Vectors.cpp.dir/Vectors.cpp.i
.PHONY : Vectors.cpp.i

Vectors.s: Vectors.cpp.s
.PHONY : Vectors.s

# target to generate assembly for a file
Vectors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Vectors.cpp.dir/build.make CMakeFiles/Vectors.cpp.dir/Vectors.cpp.s
.PHONY : Vectors.cpp.s

cpp_templates.o: cpp_templates.cpp.o
.PHONY : cpp_templates.o

# target to build an object file
cpp_templates.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp_templates.cpp.dir/build.make CMakeFiles/cpp_templates.cpp.dir/cpp_templates.cpp.o
.PHONY : cpp_templates.cpp.o

cpp_templates.i: cpp_templates.cpp.i
.PHONY : cpp_templates.i

# target to preprocess a source file
cpp_templates.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp_templates.cpp.dir/build.make CMakeFiles/cpp_templates.cpp.dir/cpp_templates.cpp.i
.PHONY : cpp_templates.cpp.i

cpp_templates.s: cpp_templates.cpp.s
.PHONY : cpp_templates.s

# target to generate assembly for a file
cpp_templates.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/cpp_templates.cpp.dir/build.make CMakeFiles/cpp_templates.cpp.dir/cpp_templates.cpp.s
.PHONY : cpp_templates.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.cpp.dir/build.make CMakeFiles/main.cpp.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.cpp.dir/build.make CMakeFiles/main.cpp.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.cpp.dir/build.make CMakeFiles/main.cpp.dir/main.cpp.s
.PHONY : main.cpp.s

mainmain.o: mainmain.cpp.o
.PHONY : mainmain.o

# target to build an object file
mainmain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainmain.cpp.dir/build.make CMakeFiles/mainmain.cpp.dir/mainmain.cpp.o
.PHONY : mainmain.cpp.o

mainmain.i: mainmain.cpp.i
.PHONY : mainmain.i

# target to preprocess a source file
mainmain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainmain.cpp.dir/build.make CMakeFiles/mainmain.cpp.dir/mainmain.cpp.i
.PHONY : mainmain.cpp.i

mainmain.s: mainmain.cpp.s
.PHONY : mainmain.s

# target to generate assembly for a file
mainmain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mainmain.cpp.dir/build.make CMakeFiles/mainmain.cpp.dir/mainmain.cpp.s
.PHONY : mainmain.cpp.s

smartpointers.o: smartpointers.cpp.o
.PHONY : smartpointers.o

# target to build an object file
smartpointers.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smartpointers.cpp.dir/build.make CMakeFiles/smartpointers.cpp.dir/smartpointers.cpp.o
.PHONY : smartpointers.cpp.o

smartpointers.i: smartpointers.cpp.i
.PHONY : smartpointers.i

# target to preprocess a source file
smartpointers.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smartpointers.cpp.dir/build.make CMakeFiles/smartpointers.cpp.dir/smartpointers.cpp.i
.PHONY : smartpointers.cpp.i

smartpointers.s: smartpointers.cpp.s
.PHONY : smartpointers.s

# target to generate assembly for a file
smartpointers.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/smartpointers.cpp.dir/build.make CMakeFiles/smartpointers.cpp.dir/smartpointers.cpp.s
.PHONY : smartpointers.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... 2DArrays.cpp"
	@echo "... 3.1_backup.cpp"
	@echo "... Arrays.cpp"
	@echo "... Ass3_1.cpp"
	@echo "... Assignment4_1.cpp"
	@echo "... Circles.cpp"
	@echo "... DynamicMemoryMgmt.cpp"
	@echo "... ExceptionHandler.cpp"
	@echo "... IO.cpp"
	@echo "... IO2.cpp"
	@echo "... MyClass.cpp"
	@echo "... Palindrome.cpp"
	@echo "... Pointers.cpp"
	@echo "... PointersDemo.cpp"
	@echo "... RecursiveFunctions.cpp"
	@echo "... STL_Sort.cpp"
	@echo "... StringsManipulation.cpp"
	@echo "... StructDemo.cpp"
	@echo "... Vectors.cpp"
	@echo "... cpp_templates.cpp"
	@echo "... main.cpp"
	@echo "... mainmain.cpp"
	@echo "... smartpointers.cpp"
	@echo "... stacks"
	@echo "... 2DArrays.o"
	@echo "... 2DArrays.i"
	@echo "... 2DArrays.s"
	@echo "... 3.1_backup.o"
	@echo "... 3.1_backup.i"
	@echo "... 3.1_backup.s"
	@echo "... Arrays.o"
	@echo "... Arrays.i"
	@echo "... Arrays.s"
	@echo "... Ass3_1.o"
	@echo "... Ass3_1.i"
	@echo "... Ass3_1.s"
	@echo "... Assignment4_1.o"
	@echo "... Assignment4_1.i"
	@echo "... Assignment4_1.s"
	@echo "... Circles.o"
	@echo "... Circles.i"
	@echo "... Circles.s"
	@echo "... DynamicMemoryMgmt.o"
	@echo "... DynamicMemoryMgmt.i"
	@echo "... DynamicMemoryMgmt.s"
	@echo "... ExceptionHandler.o"
	@echo "... ExceptionHandler.i"
	@echo "... ExceptionHandler.s"
	@echo "... IO.o"
	@echo "... IO.i"
	@echo "... IO.s"
	@echo "... IO2.o"
	@echo "... IO2.i"
	@echo "... IO2.s"
	@echo "... MyClass.o"
	@echo "... MyClass.i"
	@echo "... MyClass.s"
	@echo "... Palindrome.o"
	@echo "... Palindrome.i"
	@echo "... Palindrome.s"
	@echo "... Pointers.o"
	@echo "... Pointers.i"
	@echo "... Pointers.s"
	@echo "... PointersDemo.o"
	@echo "... PointersDemo.i"
	@echo "... PointersDemo.s"
	@echo "... RecursiveFunctions.o"
	@echo "... RecursiveFunctions.i"
	@echo "... RecursiveFunctions.s"
	@echo "... STL_Sort.o"
	@echo "... STL_Sort.i"
	@echo "... STL_Sort.s"
	@echo "... StringsManipulation.o"
	@echo "... StringsManipulation.i"
	@echo "... StringsManipulation.s"
	@echo "... StructDemo.o"
	@echo "... StructDemo.i"
	@echo "... StructDemo.s"
	@echo "... Vectors.o"
	@echo "... Vectors.i"
	@echo "... Vectors.s"
	@echo "... cpp_templates.o"
	@echo "... cpp_templates.i"
	@echo "... cpp_templates.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainmain.o"
	@echo "... mainmain.i"
	@echo "... mainmain.s"
	@echo "... smartpointers.o"
	@echo "... smartpointers.i"
	@echo "... smartpointers.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

